# Define a global platform for your project
platform :ios, '13.0'

target 'TraeNoteBook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TraeNoteBook
  pod 'MJRefresh'
  pod 'SVProgressHUD'

  target 'TraeNoteBookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TraeNoteBookUITests' do
    # Pods for testing
  end

end
